site_name: Dhscanner
theme:
  name: material
  custom_dir: overrides 
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - toc.follow
    - search.highlight
    - content.code.copy
extra:
  logo:
    image: logo.png
extra_css:
  - stylesheets/custom.css
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting_started/introduction.md
      - CI/CD: getting_started/ci_cd.md
      - CLI: getting_started/cli.md
  - Dhscanner Internals:
      - Design: dhscanner_internals/design.md
      - Rules: dhscanner_internals/rules.md
  - Research:
      - Scanning at scale: research/scanning_at_scale.md
      - Heavy workloads: research/heavy_workloads.md
  - Contribution:
      - Usage: contribution/usage.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.superfences
  - pymdownx.details
