site_name: Dhscanner
theme:
  name: material
  custom_dir: overrides 
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - toc.follow
    - search.highlight
    - content.code.copy
extra:
  logo:
    image: logo.png
extra_css:
  - stylesheets/custom.css
nav:
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - CI/CD: getting-started/introduction.md
      - CLI: getting-started/installation.md
  - Adding Frameworks:
      - Commands: cli/commands.md
      - Examples: cli/examples.md
  - Dhscanner Atoms:
      - Overview: write-your-own-rules/overview.md
      - Rule Examples: write-your-own-rules/rule-examples.md
  - Research:
      - Scanning at scale: research/articles.md
      - Heavy workloads: research/vulnerability-patterns.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.superfences
  - pymdownx.details
